mongo:
  image: mongo
website:
  build: ./Website
  ports:
   - "8080:8080"
  volumes:
   - ./Website/App:/App
data_api:
  build: ./DataApi
  ports:
   - "5000:5000"
  volumes:
   - ./DataApi/App:/App
  links:
   - mongo
